version: 2
updates:
- package-ecosystem: npm
  directory: "/template"
  schedule:
    interval: monthly
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "21:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ava
    versions:
    - ">= 3.a, < 4"
