
image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "export CI=false" >> ~/.bashrc && source ~/.bashrc && yarn && yarn test
  - init: sudo npm i -g npm-check-updates esvu && yes | esvu && exit

vscode:
  extensions:
    - firsttris.vscode-jest-runner
