version: 2

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm i
      - run: bash test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
