version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: gengjiawen/v8-build:arm64
    steps:
      - checkout
      - run: npx envinfo
      - run: yarn
      - run:
          name: test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
