version: 2

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npx envinfo
      - run: yarn
      - run:
          name: test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
